services:
  horrorCache:
    container_name: horror_cache
    build: .
    image: horror_cache
    ports:
      - "8000:8000"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
    restart: unless-stopped

